name: flutter_application_ujicobauts2
description: A new Flutter project - FinTrack App with Firebase Integration
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icon Packages
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # State Management
  provider: ^6.1.2

  # Firebase Core & Authentication
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1

  # API (Networking)
  dio: ^5.4.0

  # Chart & Data Visualization
  fl_chart: ^0.64.0

  # Date & Currency Formatter
  intl: ^0.19.0

  # (Opsional) Firebase Cloud Messaging (notifikasi)
  firebase_messaging: ^14.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/fintrack_logo.png


  # Tambahkan font custom kalau nanti ingin branding FinTrack
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Regular.ttf