name: flutter_application_ujicobauts2
description: A new Flutter project - FinTrack App with Firebase Integration
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.3

  # UI & Icon Packages
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # State Management
  provider: ^6.1.2

  # Firebase Core & Authentication
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.3.0

  # Firebase Cloud Firestore
  cloud_firestore: ^4.17.5

  # Firebase Messaging & Local Notifications
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.1.2

  # API (Networking)
  dio: ^5.4.0
  url_launcher: ^6.3.1

  # Chart & Data Visualization
  fl_chart: ^0.64.0

  # Date & Currency Formatter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/fintrack_logo.png
    - assets/images/google_logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
